Repository rcltech/owl, pull requests merged in 2019-10, with the labels that each got.

#27 change project name
  .travis.yml
  README.md
  express-app/README.md
  express-app/index.js
  express-app/package.json
Labels: enhancement

#23 initialize dummy user auth
  express-app/middleware/authUser.js
  express-app/models/booking.js
  express-app/package-lock.json
  express-app/package.json
  express-app/routes/booking.js
  express-app/test/booking.spec.js
Labels: enhancement, express-app

#29 write get request handler to read bookings for a particular user
  express-app/README.md
  express-app/routes/booking.js
  express-app/test/booking.spec.js
Labels: enhancement, express-app

#34 serve react on express
  .travis.yml
  express-app/.gitignore
  express-app/index.js
  express-app/package-lock.json
  express-app/package.json
  express-app/test/booking.spec.js
  express-app/test/room.spec.js
  express-app/test/root.spec.js
  react-app/package-lock.json
Labels: enhancement

#35 fix travis
  .gitignore
  .prettierrc.yml
  .travis.yml
  README.md
  express-app/README.md
  express-app/package.json
  package-lock.json
  package.json
Labels: bug, urgent

#36 create apollo context in react app
  .travis.yml
  react-app/package-lock.json
  react-app/package.json
  react-app/src/App.js
  react-app/src/index.js
Labels: enhancement, react-app

#38 integrate ladybird directly in react
  .travis.yml
  react-app/package-lock.json
  react-app/package.json
  react-app/src/App.js
  react-app/src/index.js
Labels: enhancement

#39 Frontend
  .travis.yml
  react-app/package-lock.json
  react-app/package.json
  react-app/public/index.html
  react-app/src/App.css
  react-app/src/App.js
  react-app/src/components/complement/About.js
  react-app/src/components/complement/Contact.js
  react-app/src/components/complement/Header.js
  react-app/src/components/complement/Help.js
  react-app/src/components/complement/InfoSection.js
  react-app/src/components/complement/Member.js
  react-app/src/components/complement/Members.js
  react-app/src/components/complement/NavBar.js
  react-app/src/components/complement/ProductDescription.js
  react-app/src/components/main/ChooseDate.js
  react-app/src/components/main/ChooseRoom.js
  react-app/src/components/main/ChooseTime.js
  react-app/src/components/main/Homepage.js
  react-app/src/functions/getRooms.js
  react-app/src/images/logo.png
  react-app/src/images/team-members/sean.jpg
  react-app/src/images/team-members/sid.png
  react-app/src/images/team-members/utkarsh.png
  react-app/src/images/team-members/welvin.png
  react-app/src/index.js
Labels: enhancement, react-app

#44 integrate docker and gh-pages deploys
  .travis.yml
  react-app/.dockerignore
  react-app/Dockerfile
  react-app/README.md
  react-app/package-lock.json
  react-app/package.json
  react-app/public/CNAME
  react-app/public/manifest.json
  react-app/src/App.js
  react-app/src/components/main/ChooseTime.js
  react-app/src/functions/getRooms.js
Labels: enhancement
