Repository rcltech/owl, pull requests merged in 2019-11, with the labels that each got.

#48 implement apollo client
  react-app/src/App.js
  react-app/src/components/main/BookingSummary.js
  react-app/src/components/main/ChooseTime.js
  react-app/src/functions/getRooms.js
  react-app/src/functions/postBooking.js
  react-app/src/index.js
Labels: enhancement, express-app

#49 update room type to reflect changes in phoenix
  react-app/src/components/main/BookingSummary.js
  react-app/src/components/main/ChooseRoom.js
  react-app/src/components/main/ChooseTime.js
Labels: enhancement

#45 Frontend #2
  react-app/package-lock.json
  react-app/package.json
  react-app/src/App.js
  react-app/src/components/complement/DatePicker.js
  react-app/src/components/complement/Header.js
  react-app/src/components/complement/Menu.js
  react-app/src/components/complement/Modals.js
  react-app/src/components/complement/NavBar.js
  react-app/src/components/complement/Timepicker.js
  react-app/src/components/main/BookingSummary.js
  react-app/src/components/main/ChooseDate.js
  react-app/src/components/main/ChooseRoom.js
  react-app/src/components/main/ChooseTime.js
  react-app/src/components/main/Homepage.js
  react-app/src/functions/getRooms.js
  react-app/src/functions/validateTime.js
  react-app/src/images/apps/sls.png
  react-app/src/images/modals/fail.png
  react-app/src/images/modals/success.png
  react-app/src/index.js
Labels: enhancement

#50 add a simple loader for screen loading
  react-app/src/components/complement/Loader.js
  react-app/src/images/double-ring.gif
Labels: enhancement

#53 fix auth id storage bug
  src/App.js
Labels: bug

#55 fix error caused by unnecessary graphql query
  src/App.js
Labels: bug
